### ISSUE TITLE
Humanize alert annotation values

### ISSUE THREAD

**Issue by mxinden** [kubernetes-monitoring/kubernetes-mixin#100]
Some alert annotations use the `$value` of the query as is. Instead one could pipe a value in bytes through [`humanize1024`](https://prometheus.io/docs/prometheus/latest/configuration/template_reference/#numbers).

E.g. `KubePersistentVolumeUsageCritical`:

``` yaml
            annotations: {
              message: 'The PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in Namespace {{ $labels.namespace }} is only {{ printf "%0.0f" $value }}% free.',
},
```

Originated from https://bugzilla.redhat.com/show_bug.cgi?id=1634299.
