### ISSUE TITLE
Add Job and CronJob rules

### ISSUE THREAD

**Issue by StevenACoffman** [kubernetes-monitoring/kubernetes-mixin#24]
Hello, as mentioned in kubernetes slack on `#monitoring-mixin` channel, I don't see any thing equivalent to:
+ [Job Rules](https://github.com/camilb/prometheus-kubernetes/blob/master/assets/prometheus/rules/job.rules)

I've never encountered ksonnet before, so I'm not sure if I can translate that job file in a timely fashion. I'm also not sure whether it should be added to [this existing file](
https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/alerts/apps_alerts.libsonnet#L8) or if it warrants putting it in a completely separate file for jobs. I would appreciate any guidance or suggestions.

```
groups:
- name: job.rules
  rules:
  - alert: CronJobRunning
    expr: time() -kube_cronjob_next_schedule_time > 3600
    for: 1h
    labels:
      severity: warning
    annotations:
      description: CronJob {{$labels.namespaces}}/{{$labels.cronjob}} is taking more than 1h to complete
      summary: CronJob didn't finish after 1h

  - alert: JobCompletion
    expr: kube_job_spec_completions - kube_job_status_succeeded  > 0
    for: 1h
    labels:
      severity: warning
    annotations:
      description: Job completion is taking more than 1h to complete
        cronjob {{$labels.namespaces}}/{{$labels.job}}
      summary: Job {{$labels.job}} didn't finish to complete after 1h

  - alert: JobFailed
    expr: kube_job_status_failed  > 0
    for: 1h
    labels:
      severity: warning
    annotations:
      description: Job {{$labels.namespaces}}/{{$labels.job}} failed to complete
      summary: Job failed
```
