### ISSUE TITLE
EKS - Almost All Grafana Graphs Partly Broken

### ISSUE THREAD

**Issue by jseiser** [kubernetes-monitoring/kubernetes-mixin#315]
EKS Version: 1.14

- Prometheus:
- - Installed via helm/stable
- - Version v2.14.0

- Grafana
- - installed via helm/stable
- - Version 6.5.2

I generated the files following 'Generate config files' and imported them into Grafana using the values.yaml

```
    dashboards:
      default:
        cluster-autoscaler:
          gnetId: 3831
          revision: 1
          datasource: Prometheus
        workload-total:
          url: "https://bitbucket.org/!api/2.0/snippets/jseiser/rn8k6R/3e3147dadbd58610cdedbf7eb3fc3a643f26eba0/files/workload-total.json"

```
Things That Do Not work, Per dashboard

- Kubernetes / API server
- - Nothing Works
- Kubernetes / Compute Resources / Cluster 
- - CPU Utilization
- - memory Utilization
- - CPU Usage
- Kubernetes / Compute Resources / Namespace (Pods) 
- - CPU Usage
- - CPU Quota
- Kubernetes / Compute Resources / Namespace (Workloads)
- - Nothing Works
- - Nothing available under type
- Kubernetes / Compute Resources / Node (Pods)
- - CPU Usage
- - Memory Usage w/o cache
- Kubernetes / Compute Resources / Pod 
- - CPU Usage
- Kubernetes / Compute Resources / Workload
- - Workload Empty
- - Type Empty
- - No Graphs Work
- Kubernetes / Controller Manager
- - Nothing Works
- Kubelet
- - Nothing Works
- Kubernetes / Networking / Namespace (Workload)
- - Type Empty
- - No Graphs work
- Kubernetes / Networking / Workload
- - Work Empty
- - Type Empty
- - No graphs work
- Kubernetes / Persistent Volumes 
- - Namespace Empty
- - PersisentVolumeClaim Empty
- - No Graphs Work
- Kubernetes / Pods
- - No Graphs Work
- Kubernetes / Proxy
- - No Graphs Work
- Kubernetes / Scheduler 
- - No Graphs Works
- Kubernetes / StatefulSets
- - Namespace == None
- - No Graphs Work

My Generated Dashboards

```
        apiserver:
          url: "https://bitbucket.org/!api/2.0/snippets/jseiser/n7zyKd/2f84053918a958efbc9f45bd6aafa28f9a42f19f/files/apiserver.json"
        cluster-total:
          url: "https://bitbucket.org/!api/2.0/snippets/jseiser/n7zyKd/2f84053918a958efbc9f45bd6aafa28f9a42f19f/files/cluster-total.json"
        controller-manager:
          url: "https://bitbucket.org/!api/2.0/snippets/jseiser/n7zyKd/2f84053918a958efbc9f45bd6aafa28f9a42f19f/files/controller-manager.json"
        k8s-resources-cluster:
          url: "https://bitbucket.org/!api/2.0/snippets/jseiser/n7zyKd/2f84053918a958efbc9f45bd6aafa28f9a42f19f/files/k8s-resources-cluster.json"
        k8s-resources-namespace:
          url: "https://bitbucket.org/!api/2.0/snippets/jseiser/n7zyKd/2f84053918a958efbc9f45bd6aafa28f9a42f19f/files/k8s-resources-namespace.json"
        k8s-resources-node:
          url: "https://bitbucket.org/!api/2.0/snippets/jseiser/bLzE6r/050092b49ac6f80e2927d3fc15d47d10b3afd8c0/files/k8s-resources-node.json"
        k8s-resources-pod:
          url: "https://bitbucket.org/!api/2.0/snippets/jseiser/bLzE6r/050092b49ac6f80e2927d3fc15d47d10b3afd8c0/files/k8s-resources-pod.json"
        k8s-resources-workload:
          url: "https://bitbucket.org/!api/2.0/snippets/jseiser/bLzE6r/050092b49ac6f80e2927d3fc15d47d10b3afd8c0/files/k8s-resources-workload.json"
        k8s-resources-workloads-namespace:
          url: "https://bitbucket.org/!api/2.0/snippets/jseiser/bLzE6r/050092b49ac6f80e2927d3fc15d47d10b3afd8c0/files/k8s-resources-workloads-namespace.json"
        kubelet:
          url: "https://bitbucket.org/!api/2.0/snippets/jseiser/bLzE6r/050092b49ac6f80e2927d3fc15d47d10b3afd8c0/files/kubelet.json"
        namespace-by-pod:
          url: "https://bitbucket.org/!api/2.0/snippets/jseiser/bLzE6r/050092b49ac6f80e2927d3fc15d47d10b3afd8c0/files/namespace-by-pod.json"
        namespace-by-workload:
          url: "https://bitbucket.org/!api/2.0/snippets/jseiser/bLzE6r/050092b49ac6f80e2927d3fc15d47d10b3afd8c0/files/namespace-by-workload.json"
        persistentvolumesusage:
          url: "https://bitbucket.org/!api/2.0/snippets/jseiser/rn8k6R/3e3147dadbd58610cdedbf7eb3fc3a643f26eba0/files/persistentvolumesusage.json"
        pod-total:
          url: "https://bitbucket.org/!api/2.0/snippets/jseiser/rn8k6R/3e3147dadbd58610cdedbf7eb3fc3a643f26eba0/files/pod-total.json"
        pods:
          url: "https://bitbucket.org/!api/2.0/snippets/jseiser/rn8k6R/3e3147dadbd58610cdedbf7eb3fc3a643f26eba0/files/pods.json"
        proxy:
          url: "https://bitbucket.org/!api/2.0/snippets/jseiser/rn8k6R/3e3147dadbd58610cdedbf7eb3fc3a643f26eba0/files/proxy.json"
        scheduler:
          url: "https://bitbucket.org/!api/2.0/snippets/jseiser/rn8k6R/3e3147dadbd58610cdedbf7eb3fc3a643f26eba0/files/scheduler.json"
        statefulset:
          url: "https://bitbucket.org/!api/2.0/snippets/jseiser/rn8k6R/3e3147dadbd58610cdedbf7eb3fc3a643f26eba0/files/statefulset.json"
        workload-total:
          url: "https://bitbucket.org/!api/2.0/snippets/jseiser/rn8k6R/3e3147dadbd58610cdedbf7eb3fc3a643f26eba0/files/workload-total.json"
```

The work you guys have done here is amazing, but I just want to confirm this should work on EKS, using the versions of grafana and prometheus I have deployed?
