### ISSUE TITLE
Empty graphs in USE Method dashboards 

### ISSUE THREAD

**Issue by serathius** [kubernetes-monitoring/kubernetes-mixin#38]
All graphs beside Disk Utilization are empty.
Looks like queries using `group_left` are all returning no results.
Example:
```yaml
record: node:node_cpu_utilisation:avg1m
expr: 1
  - avg by(node) (rate(node_cpu{job="node-exporter",mode="idle"}[1m])
  * on(namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:)
```
