### ISSUE TITLE
`code_verb:apiserver_request_total:increase30d` loads (too) many samples

### ISSUE THREAD

**Issue by beorn7** [kubernetes-monitoring/kubernetes-mixin#411]
This is about the following rule:

```YAML
record: code_verb:apiserver_request_total:increase30d
expr: sum by(code, verb) (increase(apiserver_request_total{job="default/kubernetes"}[30d]))
```

apiserver_request_total has a surprisingly high cardinality (easily into the thousands for moderate cluster sizes). The rule above therefore loads 30d of samples of thousands of series into memory, which easily breaches the default 50M limit.

The rule is only used in the apiserver dashboard (to display the availability over the last 30d). It's not even used for the “important” part of alerting.

It would be good to find a way to work around this problem.

**Comment by beorn7** [comment]
Brainstormed idea:

```YAML
- record: code_verb:apiserver_request_total:increase1h
  expr: sum by(code, verb) (increase(apiserver_request_total{job="default/kubernetes"}[1h]))
- record: code_verb:apiserver_request_total:increase30d
  expr: avg_over_time(code_verb:apiserver_request_total:increase1h[30d]) * 24 * 30
```

**Comment by metalmatze** [comment]
Did you try the fixes I added in #403? 
Even with those improvements the problems still persists?

**Comment by beorn7** [comment]
#403 was merged just a few seconds too late to make it into my production deploy. I'll try it out.

My idea above will actually reduce the work done in total a lot, but it has the problem that you need to let it run for a month to get the result (or wait for rule backfilling…).

So I guess, for now #403 is the preferred approach. I'll try it out.

**Comment by csmarchbanks** [comment]
Not all of the queries in #403 work for me, specifically `sum by (code, verb) (increase(apiserver_request_total{code=~"2..", job="apiserver", verb="LIST"}[30d]))` loads too many samples. Anything with more than [8d] is failing on the server I tried.

**Comment by beorn7** [comment]
I guess that's the problem with the approach: The "sharding" is not uniform. With my over-time idea, you are cutting the 30d into 720 equal hourly pieces (at the price of requiring that rule being present for a month before you get proper results – or wait for retroactive rule evaluation).

**Comment by metalmatze** [comment]
What are you suggesting? Not sure I can get an idea how to improve things from your comment.
I guess for a lot of people 7d availability would be good enough too?
I could dedicate some time again so that we can compute the windows according to days in the availability. Then people could simply run with 7d for example.

**Comment by beorn7** [comment]
I had to go down to 3d to make our production servers not choke.

(In general, I'd be happy to tweak my servers for heavy production use cases, but in this case, the heavy weight query is for a single dashboard and not even for the alerts. That's why I'm kind of keen to make it _much_ more affordable.)

**Comment by beorn7** [comment]
My over-time idea was up there. Quote:

```YAML
- record: code_verb:apiserver_request_total:increase1h
  expr: sum by(code, verb) (increase(apiserver_request_total{job="default/kubernetes"}[1h]))
- record: code_verb:apiserver_request_total:increase30d
  expr: avg_over_time(code_verb:apiserver_request_total:increase1h[30d]) * 24 * 30
```

As soon as I find a few moments, I'll play with it.

**Comment by csmarchbanks** [comment]
I have had success using the intermediary rules @beorn7 suggests in similar applications. Being forced to wait 30 days is a bit of a bummer, but hasn't been too big of a deal the other times I have done this.

**Comment by den-is** [comment]
even applying @beorn7 suggestion didn't help much. started to use couple percents less.
![Screen Shot 2020-05-06 at 20 51 37](https://user-images.githubusercontent.com/5287237/81205187-6565c680-8fdb-11ea-93a7-3fbc5c275d4d.png)

**Comment by beorn7** [comment]
As an additional data point:

Today, I deployed the current state of master as is (697afa2c566252c08934b53a158b8c22be6c9051) to our beefiest production clusters, and it just worked. I couldn't even see any dramatic increase in CPU usage (but our Prometheis are fairly busy with many recording rules anyway, the dramatic increase seen by @den-is might be so visible because there seemed to be very little ongoing on the server before).

**Comment by den-is** [comment]
Indeed, my `stable/prometheus-operator` deploy is 99% pure your work, guys. Almost not adding anything. And that deploy/cluster is not doing anything epic.
Not only I see such a drastic change in CPU usage, but  many others, in 1001 similar issues opened https://github.com/helm/charts/pull/22003#issuecomment-616727149

JFYI, I'm running Prometheus 2.17.x much before upgrading to this version of the "rules".
Yesterday I was "forced" to upgrade to the latest version + Prometheus 2.18.0

**Comment by beorn7** [comment]
And another data point: Apparently, we are very close to the default limit of 50M samples loaded because _occasionally_ the rule evaluation fails. I'll bump up the limit for now, but the general concern stays: Should we have a fairly expensive query in the mixin by default that is only used for a few panels in one dashboard?

**Comment by metalmatze** [comment]
Hey, I'm still thinking about this problem and sometimes don't know whether or not to simply remove the rules for now. 
On the other hand, I think having the availability calculated is very helpful, and only with the availability are we able to talk about our remaining error budget.
I'll try to update the rules and check if I can add @beorn7 original idea about splitting the query into two with 1h and 30d :)

**Comment by beorn7** [comment]
Great. Let me know how it is going and where I can help.

**Comment by songrijie** [comment]
Me too... getting the same issue even with #403

**Comment by metalmatze** [comment]
@beorn7, correct me if I'm wrong but with your approach, we only ever get the average of requests made over 30d for 1h windows, no? Having an outage will show significantly different in terms of availability percentage because the average of 1h won't be the same of the count overall 30d. 

After all, my goal is to have a rather details and correct measurement of availability to be able to calculate the error budget appropriately, which is what a lot of discussions should be based on.

**Comment by beorn7** [comment]
My suggestion is to replace

```YAML
record: code_verb:apiserver_request_total:increase30d
expr: sum by(code, verb) (increase(apiserver_request_total{job="default/kubernetes"}[30d]))
```

with

```YAML
- record: code_verb:apiserver_request_total:increase1h
  expr: sum by(code, verb) (increase(apiserver_request_total{job="default/kubernetes"}[1h]))
- record: code_verb:apiserver_request_total:increase30d
  expr: avg_over_time(code_verb:apiserver_request_total:increase1h[30d]) * 24 * 30
```

Once `code_verb:apiserver_request_total:increase1h` has been populated for 30d, the old and the new `code_verb:apiserver_request_total:increase30d` should yield very similar results. The only difference is a 1h-long "fade out" at the beginning and end of the 30d range, which shouldn't really matter in practice.

Have you seen differences in practice, or is your conclusion just based on theoretical considerations? If the latter, could you explain in more detail?

The new approach is even more flexible because it's now probably cheap enough to calculate other time ranges than 30d ad hoc, e.g. you could do `avg_over_time(code_verb:apiserver_request_total:increase1h[7d]) * 24 * 7` without a recording rule if you wanted to inspect the last week.
