### ISSUE TITLE
Added Feature: kube-storage alerts rule

### ISSUE THREAD

**Issue by bshah0408** [kubernetes-monitoring/kubernetes-mixin#676]
How would I add my custom rules to this config, where I am using [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) 

The config rule I am trying to add would be : 

```
  # Please add ignored mountpoints in node_exporter parameters like
  # "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|run)($|/)".
  # Same rule using "node_filesystem_free_bytes" will fire when disk fills for non-root users.
  - alert: HostOutOfDiskSpace
    expr: (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 20 and ON (instance, device, mountpoint) node_filesystem_readonly == 0
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Host out of disk space (instance {{ $labels.instance }})
      description: "Disk is almost full (< 20% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"     
```  
I was thinking should it be added to : 

https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L76-L92

or someone can add  this rule in upcoming upgrade. 

Please let me know 
Thanks 🔢
