### ISSUE TITLE
Runbook missing for TargetDown

### ISSUE THREAD

**Issue by spjspjspj** [kubernetes-monitoring/kubernetes-mixin#725]
The runbook_url on TargetDown alert doesn't link to its runbook:

https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-targetdown

```
alert: TargetDown
expr: 100
  * (count by(job, namespace, service) (up == 0) / count by(job, namespace, service)
  (up)) > 10
for: 10m
labels:
  severity: warning
  team: auto_routed_using_namespace
annotations:
  description: '{{ printf "%.4g" $value }}% of the {{ $labels.job }}/{{ $labels.service
    }} targets in {{ $labels.namespace }} namespace are down.'
  runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-targetdown
  summary: One or more targets are unreachable.
```
